config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :stats
  resources :games
  resources :teams
  resources :players

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :players, through: :teams
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "240x240>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  belongs_to :team
  has_many :stats
end

app/models/stat.rb
class Stat < ActiveRecord::Base

  has_attached_file :file
  validates_attachment_content_type :file, content_type: 'text/plain'
  validates_presence_of :player_id
  validates_presence_of :game_id

  belongs_to :player, foreign_key: [:player_id]
  belongs_to :game, foreign_key: [:game_id]
end

app/models/team.rb
class Team < ActiveRecord::Base

  has_many :stats, through: :games
  has_many :players, foreign_key: [:player_1, :player_2, :player_3, :player_4, :player_5, :player_6, :player_7, :player_8, :player_9, :player_10, :player_11, :player_12, :player_13, :player_14]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
    @teams = Team.all
  end

  def show
    @teams = Team.all
  end

  def new
    @game = Game.new
    @team = Team.all
  end

  def edit
    @team = Team.all
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
       redirect_to @game, notice: 'Game was successfully updated.'
    else
     render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:date, :time, :stadium, :attendees, :home_team, :away_team, :round, :home_team_score, :away_team_score, :ht_q1, :ht_q2, :ht_q3, :ht_q4, :at_q1, :at_q2, :at_q3, :at_q4, :referee)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show
    @players = Player.all
    @stats = Stat.all
  end

  def new
    @player = Player.new
  end

  def edit
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
     render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :height, :dob, :nationality, :position, :p_number, :avatar)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]

  def index
    @stats = Stat.all
    @players = Player.all
    @games = Game.all
    @teams = Team.all
  end

  def show
    @players = Player.all
    @games = Game.all
    @teams = Team.all
  end

  def new
    @stat = Stat.new
    @games = Game.all
    @players = Player.all
  end

  def edit
    @games = Game.all
    @players = Player.all
  end

  def create
    @stat = Stat.new(stat_params)
    if @stat.save
      redirect_to @stat, notice: 'Stat was successfully created.'
    else
      render :new
    end
  end

  def update
    if @stat.update(stat_params)
     redirect_to @stat, notice: 'Stat was successfully updated.'
    else
     render :edit
    end
  end

  def destroy
    @stat.destroy
     redirect_to stats_url, notice: 'Stat was successfully destroyed.'
    end
  end

  private
    def set_stat
      @stat = Stat.find(params[:id])
    end

    def stat_params
      params.require(:stat).permit(:player_id, :game_id, :mins_played, :points, :two_p_field_goals, :three_p_field_goals, :free_throws, :rebounds_off, :rebounds_def, :rebounds_total, :assists, :steals, :turnovers, :blocks_in_favor, :blocks_against, :fouls_commited, :fouls_received, :pir, :file)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
    @players = Player.all
    @teams = Team.all
  end

  def show
    @players = Player.all
    @games = Game.all
    @teams = Team.all

  end

  def new
    @team = Team.new
    @player = Player.all
  end

  def edit
    @player = Player.all
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to @team, notice: 'Team was successfully created.'
    else
     render :new
    end
  end

  def update
    if @team.update(team_params)
      redirect_to @team, notice: 'Team was successfully updated.'
    else
      render :edit
    end

  end

  def destroy
    @team.destroy
    redirect_to teams_url, notice: 'Team was successfully destroyed.'
  end


  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name, :president, :coach, :stadium, :address, :phone, :player_1, :player_2, :player_3, :player_4, :player_5, :player_6, :player_7, :player_8, :player_9, :player_10, :player_11, :player_12, :player_13, :player_14)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table id="sortable_table" class="table table-condensed table-bordered table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Stadium</th>
      <th>Attendees</th>
      <th>Home team</th>
      <th>Away team</th>
      <th>Round</th>
      <th>Home team score</th>
      <th>Away team score</th>
      <th>Ht q1</th>
      <th>Ht q2</th>
      <th>Ht q3</th>
      <th>Ht q4</th>
      <th>At q1</th>
      <th>At q2</th>
      <th>At q3</th>
      <th>At q4</th>
      <th>Referee</th>
      <th>Show more</th>
      <th>Edit</th>
      <th>Remove</th>

    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.date %></td>
        <td><%= game.time %></td>
        <td><%= game.stadium %></td>
        <td><%= game.attendees %></td>
        <td><% @teams.each do |team| %>
          <% if game.home_team == team.id  %>
            <%= link_to team.name , team %>
            <% end %>
        <% end %></td>
        <td><% @teams.each do |team| %>
          <% if game.away_team == team.id  %>
            <%= link_to team.name , team %>
            <% end %>
        <% end %></td>
        <td><%= game.round %></td>
        <td><%= game.home_team_score %></td>
        <td><%= game.away_team_score %></td>
        <td><%= game.ht_q1 %></td>
        <td><%= game.ht_q2 %></td>
        <td><%= game.ht_q3 %></td>
        <td><%= game.ht_q4 %></td>
        <td><%= game.at_q1 %></td>
        <td><%= game.at_q2 %></td>
        <td><%= game.at_q3 %></td>
        <td><%= game.at_q4 %></td>
        <td><%= game.referee %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script>
  $(document).ready(function() {
  $('#sortable_table').DataTable();
  });
</script>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @game.time %>
</p>

<p>
  <strong>Stadium:</strong>
  <%= @game.stadium %>
</p>

<p>
  <strong>Attendees:</strong>
  <%= @game.attendees %>
</p>

<p>
  <strong>Home team:</strong>
  <% @teams.each do |team| %>
    <% if @game.home_team == team.id  %>
      <%= link_to team.name , team %>
      <% end %>
  <% end %>
</p>

<p>
  <strong>Away team:</strong>
  <% @teams.each do |team| %>
    <% if @game.away_team == team.id  %>
      <%= link_to team.name , team %>
      <% end %>
  <% end %>
</p>

<p>
  <strong>Round:</strong>
  <%= @game.round %>
</p>

<p>
  <strong>Home team score:</strong>
  <%= @game.home_team_score %>
</p>

<p>
  <strong>Away team score:</strong>
  <%= @game.away_team_score %>
</p>

<p>
  <strong>Ht q1:</strong>
  <%= @game.ht_q1 %>
</p>

<p>
  <strong>Ht q2:</strong>
  <%= @game.ht_q2 %>
</p>

<p>
  <strong>Ht q3:</strong>
  <%= @game.ht_q3 %>
</p>

<p>
  <strong>Ht q4:</strong>
  <%= @game.ht_q4 %>
</p>

<p>
  <strong>At q1:</strong>
  <%= @game.at_q1 %>
</p>

<p>
  <strong>At q2:</strong>
  <%= @game.at_q2 %>
</p>

<p>
  <strong>At q3:</strong>
  <%= @game.at_q3 %>
</p>

<p>
  <strong>At q4:</strong>
  <%= @game.at_q4 %>
</p>

<p>
  <strong>Referee:</strong>
  <%= @game.referee %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OracleProject</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-header">
    <a class="navbar-brand" href="<%= root_url%>">Rails + Oracle = &#9889</a>
  </div>
  <div>

    <ul class="nav navbar-nav">
      <li>
        <a href="<%= root_url%>">Home</a>
      </li>
      <li>
        <a href=" <%= players_path %>">Players</a>
      </li>
      <li>
        <a href=" <%= teams_path %>">Teams</a>
      </li>
      <li>
        <a href=" <%= games_path %>">Games</a>
      </li>
      <li>
        <a href=" <%= stats_path %>">Stats</a>
      </li>
      <li class="dropdown">
        <a href="" class="dropdown-toggle" data-toggle="dropdown">
          Create
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href=" <%= new_player_url %>">New Player</a>
          </li>
          <li>
            <a href=" <%= new_team_url %>">New Team</a>
          </li>
          <li>
            <a href=" <%= new_game_url %>">New Game</a>
          </li>
          <li>
            <a href=" <%= new_stat_url %>">New Stats</a>
          </li>
          <!-- <li class = "divider"></li> -->
        </ul>
      </li>
    </ul>
    <div class="container-fluid">
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">

      </ul>
    </div>
  </div>
</div>
    </nav>
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table id="sortable_table" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th>Height</th>
      <th>Dob</th>
      <th>Nationality</th>
      <th>Position</th>
      <th>P number</th>
      <th>Show more</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= image_tag player.avatar.url(:thumb ) %></td>

        <td><%= player.name %></td>
        <td><%= player.height %></td>
        <td><%= player.dob %></td>
        <td><%= player.nationality %></td>
        <td><%= player.position %></td>
        <td><%= player.p_number %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script>
  $(document).ready(function() {
  $('#sortable_table').DataTable();
  });
</script>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">

  <div class="col-md-6">

  <% mins_played = 0 %>
  <% points = 0 %>
  <% two_goals = 0 %>
  <% three_goals = 0 %>
  <% free_throws = 0 %>
  <% rebounds_off = 0 %>
  <% rebounds_def = 0 %>
  <% rebounds_total = 0 %>
  <% assists = 0%>
  <% steals = 0 %>
  <% turnovers = 0%>
  <% blocks_in_favor = 0%>
  <% blocks_against = 0%>
  <% fouls_commited = 0%>
  <% fouls_received = 0%>
  <% pir = 0%>

  <% @stats.each do |stat| %>
  <h4>Καταχωρημένα στατιστικά του παίχτη</h4>
  <% if @player.id == stat.player_id  %>

  <p>
    <strong>Mins played:</strong>
    <%= stat.mins_played %> <% mins_played += stat.mins_played %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= stat.points %><% points += stat.points %>
  </p>

  <p>
    <strong>Two p field goals:</strong>
    <%= stat.two_p_field_goals %><% two_goals += stat.two_p_field_goals %>
  </p>

  <p>
    <strong>Three p field goals:</strong>
    <%= stat.three_p_field_goals %><% three_goals += stat.three_p_field_goals %>
  </p>

  <p>
    <strong>Free throws:</strong>
    <%= stat.free_throws %><% free_throws += stat.free_throws %>
  </p>

  <p>
    <strong>Rebounds off:</strong>
    <%= stat.rebounds_off %> <% rebounds_off += stat.rebounds_off %>
  </p>

  <p>
    <strong>Rebounds def:</strong>
    <%= stat.rebounds_def %> <% rebounds_def += stat.rebounds_def %>
  </p>

  <p>
    <strong>Rebounds total:</strong>
    <%= stat.rebounds_total %><% rebounds_total += stat.rebounds_total %>
  </p>

  <p>
    <strong>Assists:</strong>
    <%= stat.assists %> <% assists += stat.assists %>
  </p>

  <p>
    <strong>Steals:</strong>
    <%= stat.steals %> <% steals += stat.steals %>
  </p>

  <p>
    <strong>Turnovers:</strong>
    <%= stat.turnovers %><% turnovers += stat.turnovers %>
  </p>

  <p>
    <strong>Blocks in favor:</strong>
    <%= stat.blocks_in_favor %> <% blocks_in_favor += stat.blocks_in_favor %>
  </p>

  <p>
    <strong>Blocks against:</strong>
    <%= stat.blocks_against %> <% blocks_against += stat.blocks_against %>
  </p>

  <p>
    <strong>Fouls commited:</strong>
    <%= stat.fouls_commited %> <% fouls_commited += stat.fouls_commited %>
  </p>

  <p>
    <strong>Fouls received:</strong>
    <%= stat.fouls_received %> <% fouls_received += stat.fouls_received %>
  </p>

  <p>
    <strong>Pir:</strong>
    <%= stat.pir %> <% pir += stat.pir %>
  </p> <br>

  <% end %>

  <% end %>

  </div>

  <div class="col-md-6">
<p>
  <strong>Image:</strong>
  <%= image_tag @player.avatar.url(:medium) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @player.height %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @player.dob %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @player.nationality %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position %>
</p>

<p>
  <strong>P number:</strong>
  <%= @player.p_number %>
</p><br>
<h4>BarChart</h4>
<div id="chart_div"></div> <br>
<h4>Gauge Chart</h4>
<div id="chart_gauge" style="width: 400px; height: 120px;"></div>

</div>
</div>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

<script>
google.charts.load('current', {packages: ['corechart', 'bar', 'gauge']});
google.charts.setOnLoadCallback(drawAxisTickColors);

function drawAxisTickColors() {
      var data = google.visualization.arrayToDataTable([
        ['Player', '<%= @player.name %>'],
        ['Total Points', <%= points %>],
        ['Total Rebounds', <%= rebounds_total %>],
        ['Blocks in Favor', <%= blocks_in_favor %>],
        ['Fouls Committed', <%= fouls_commited %>]
      ]);

      var options = {
        title: 'BarChart w/ Points, total rebounds, blocks in favor, fouls committed',
        chartArea: {width: '60%'},
        hAxis: {
          title: 'Numbers',
          minValue: 0,
          textStyle: {
            fontSize: 12,
            color: '#4d4d4d'
          },
          titleTextStyle: {
            fontSize: 18,
            color: '#848484'
          }
        },
        vAxis: {
          title: 'City',
          textStyle: {
            fontSize: 14,
            color: '#848484'
          },
          titleTextStyle: {
            fontSize: 14,
            color: '#848484'
          }
        }
      };
      var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
</script>

<script>

     google.charts.setOnLoadCallback(drawChart);
     function drawChart() {

       var data = google.visualization.arrayToDataTable([
         ['Type', 'Value'],
         ['2 points', <%= two_goals %>],
         ['3 points', <%= three_goals %>],
         ['Free throws', <%= free_throws %>]
       ]);

       var options = {
         width: 400, height: 120,
         redFrom: 50, redTo: 60,
         yellowFrom:30, yellowTo: 49,
         minorTicks: 2
       };

       var chart = new google.visualization.Gauge(document.getElementById('chart_gauge'));

       chart.draw(data, options);

       setInterval(function() {
         data.setValue(0);
         chart.draw(data, options);
       }, 1);
       setInterval(function() {
         data.setValue(0);
         chart.draw(data, options);
       }, 1);
       setInterval(function() {
         data.setValue(0);
         chart.draw(data, options);
       }, 1);
     }
</script>

app/views/static_pages/index.html.erb
<h1>Home page</h1>
<p>A <b>Ruby on Rails app</b> using an <b>Oracle 12c database</b> hosted in Amazon Web Services to store data for Basketball players, teams, games, and player's statistics. Using <b>Google Charts</b> to display various charts for team wins/loses, player's statistics in games, etc. </p>
<p>Using <b>activerecord-oracle_enhanced-adapter</b> and <b>ruby-oci8</b> gem to connect to the Oracle database, paperclip for image upload, and bootstrap-sass.</p>
<p>Developed using <b>Git</b> for version control.</p>

<a>https://github.com/zmitzie/Rails-OracleDB</a>

app/views/stats/edit.html.erb
<h1>Editing Stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

app/views/stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stats</h1>

<table id="sortable_table" class="table table-condensed table-bordered table-hover">
  <thead>
    <tr>
      <th>File</th>
      <th>Player</th>
      <th>Game</th>
      <th>Mins played</th>
      <th>Points</th>
      <th>Two p field goals</th>
      <th>Three p field goals</th>
      <th>Free throws</th>
      <th>Rebounds off</th>
      <th>Rebounds def</th>
      <th>Rebounds total</th>
      <th>Assists</th>
      <th>Steals</th>
      <th>Turnovers</th>
      <th>Blocks in favor</th>
      <th>Blocks against</th>
      <th>Fouls commited</th>
      <th>Fouls received</th>
      <th>Pir</th>
      <th>Show more</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
    <tr>
      <td><% if stat.file.exists? %>
            <%= link_to "Download", stat.file.url(:original, false) %>
          <% else %>
            <i>No file uploaded</i>
          <% end %> </td>
      <td>
        <% @players.each do |player| %>
          <% if stat.player_id == player.id  %>
            <%= link_to player.name , player %>
          <% end %>
        <% end %>
      </td>
      <td>
        <% @games.each do |game| %>
          <% if stat.game_id == game.id  %>
            <% @teams.each do |team| %>
              <% if game.home_team == team.id  %>
                <%= team.name %>
              <% end %>
            <% end %>
            +
            <% @teams.each do |team| %>
              <% if game.away_team == team.id  %>
                <%= team.name %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </td>
      <td><%= stat.mins_played %></td>
      <td><%= stat.points %></td>
      <td><%= stat.two_p_field_goals %></td>
      <td><%= stat.three_p_field_goals %></td>
      <td><%= stat.free_throws %></td>
      <td><%= stat.rebounds_off %></td>
      <td><%= stat.rebounds_def %></td>
      <td><%= stat.rebounds_total %></td>
      <td><%= stat.assists %></td>
      <td><%= stat.steals %></td>
      <td><%= stat.turnovers %></td>
      <td><%= stat.blocks_in_favor %></td>
      <td><%= stat.blocks_against %></td>
      <td><%= stat.fouls_commited %></td>
      <td><%= stat.fouls_received %></td>
      <td><%= stat.pir %></td>
      <td><%= link_to 'Show', stat %></td>
      <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
      <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<script>
  $(document).ready(function() {
  $('#sortable_table').DataTable();
  });
</script>

app/views/stats/new.html.erb
<h1>New Stat</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>.txt File:</strong>
  <% if @stat.file.exists? %>
    <%= link_to "Download .txt file", @stat.file.url(:original, false) %>
  <% else %> <i>No file uploaded</i>
  <% end %>
</p>

<p>
  <strong>Player:</strong>
  <% @players.each do |player| %>
    <% if @stat.player_id == player.id  %>
      <%= link_to player.name , player %>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Game:</strong>
  <% @games.each do |game| %>
    <% if @stat.game_id == game.id  %>
      <% @teams.each do |team| %>
        <% if game.home_team == team.id  %>
          <%= team.name %>
        <% end %>
      <% end %>
      +
      <% @teams.each do |team| %>
        <% if game.away_team == team.id  %>
          <%= team.name %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Mins played:</strong>
  <%= @stat.mins_played %>
</p>

<p>
  <strong>Points:</strong>
  <%= @stat.points %>
</p>

<p>
  <strong>Two p field goals:</strong>
  <%= @stat.two_p_field_goals %>
</p>

<p>
  <strong>Three p field goals:</strong>
  <%= @stat.three_p_field_goals %>
</p>

<p>
  <strong>Free throws:</strong>
  <%= @stat.free_throws %>
</p>

<p>
  <strong>Rebounds off:</strong>
  <%= @stat.rebounds_off %>
</p>

<p>
  <strong>Rebounds def:</strong>
  <%= @stat.rebounds_def %>
</p>

<p>
  <strong>Rebounds total:</strong>
  <%= @stat.rebounds_total %>
</p>

<p>
  <strong>Assists:</strong>
  <%= @stat.assists %>
</p>

<p>
  <strong>Steals:</strong>
  <%= @stat.steals %>
</p>

<p>
  <strong>Turnovers:</strong>
  <%= @stat.turnovers %>
</p>

<p>
  <strong>Blocks in favor:</strong>
  <%= @stat.blocks_in_favor %>
</p>

<p>
  <strong>Blocks against:</strong>
  <%= @stat.blocks_against %>
</p>

<p>
  <strong>Fouls commited:</strong>
  <%= @stat.fouls_commited %>
</p>

<p>
  <strong>Fouls received:</strong>
  <%= @stat.fouls_received %>
</p>

<p>
  <strong>Pir:</strong>
  <%= @stat.pir %>
</p>

<%= link_to 'Edit', edit_stat_path(@stat) %> |
<%= link_to 'Back', stats_path %>